name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  semantic-release:
    name: Python Semantic Release
    runs-on: ubuntu-latest
    
    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          
      - name: Setup | Force correct release branch on workflow SHA
        run: |
          git checkout -B ${{ github.ref_name }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: List and delete pre-release tags
        id: list_tags
        run: |
          echo "Searching for tags containing 'rc', 'main', 'beta', or 'alpha'..."
          TAGS=$(git tag -l "*-rc*" "*-main*" "*-beta*", "*-alpha*")
          echo "Found tags:"  >> $GITHUB_STEP_SUMMARY
          echo "$TAGS"  >> $GITHUB_STEP_SUMMARY
          if [ -z "$TAGS" ]; then
            echo "No pre-release tags found."
            echo "tags_to_delete=" > tags.log
          else
            echo "tags_to_delete=$TAGS" > tags.log

            echo "Deleting local tags..."
            echo $TAGS | xargs -n 1 git tag -d

            echo "Deleting remote tags..."
            for TAG in $TAGS; do
              git push origin --delete $TAG || echo "Failed to delete $TAG from remote."
            done
          fi

          echo "Completed deleting all pre-release tags." >> $GITHUB_STEP_SUMMARY

      - name: Python Semantic Release
        id: semvar
        uses: pranavmishra90/semvar-docker@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_email: "195262995+facsimilab-bot@users.noreply.github.com"
          ssh_private_signing_key: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
          ssh_public_signing_key: ${{ secrets.FACSIMILAB_BOT_SSH_PUBKEY }}
          build: "true"
          vcs_release: "true"
          changelog: "true"
          commit: "true"
          tag: "true"
          push: "true"
          root_options: "-v"

      - name: Workflow Status
        run: |
          echo "## Python Semantic Release - GitHub Action" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.semvar.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          printf "Tags: \n$(git tag -l)" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "Released: ${{ steps.semvar.outputs.released }}" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
