name: Cleanup Pre-Release Tags

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  

jobs:
  delete-prerelease-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: List and delete pre-release tags
        id: list_tags
        run: |
          echo "Searching for tags containing 'rc', 'main', 'beta', or 'alpha'..."
          TAGS=$(git tag -l "*-rc*" "*-main*" "*-beta*", "*-alpha*")
          echo "Found tags:"  >> $GITHUB_STEP_SUMMARY
          echo "$TAGS"  >> $GITHUB_STEP_SUMMARY
          if [ -z "$TAGS" ]; then
            echo "No pre-release tags found."
            echo "tags_to_delete=" > tags.log
          else
            echo "tags_to_delete=$TAGS" > tags.log

            echo "Deleting local tags..."
            echo $TAGS | xargs -n 1 git tag -d

            echo "Deleting remote tags..."
            for TAG in $TAGS; do
              git push origin --delete $TAG || echo "Failed to delete $TAG from remote."
            done
          fi

      - name: Success Message
        run: |
          echo "Completed deleting all pre-release tags." >> $GITHUB_STEP_SUMMARY
